# -*- coding: utf-8 -*-
"""aitoolproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgFbRdZBXA2yAsRyr72nseAaS1lLyv_F
"""

!pip install gTTS

#!pip install pytesseract
#!apt-get install tesseract-ocr

from transformers import pipeline
from PIL import Image
from google.colab import files
import pytesseract
from gtts import gTTS
from IPython.display import Audio, display

# UPLOAD IMAGE

uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Load image
image = Image.open(image_path)

# LOAD AI MODELS

print("Loading models...")

object_detector = pipeline(
    "object-detection",
    model="facebook/detr-resnet-50"
)

image_captioner = pipeline(
    "image-text-to-text",
    model="Salesforce/blip-image-captioning-base"
)

text_generator = pipeline(
    "fill-mask",
    model="bert-base-uncased"
)

sentiment_analyzer = pipeline("sentiment-analysis")

print("Models loaded successfully!\n")

# OCR FUNCTION (TEXT EXTRACTION)

def extract_text(image):
    text = pytesseract.image_to_string(image)
    return text.strip()


#  TEXT TO SPEECH (gTTS)

def speak(text):
    tts = gTTS(text=text, lang='en')
    tts.save("output.mp3")
    return Audio("output.mp3", autoplay=True)

# PROCESS IMAGE


# Object Detection
detections = object_detector(image)
objects = [d["label"] for d in detections if d["score"] > 0.7]

# Image Captioning
caption_result = image_captioner({
    "images": image,
    "text": "Describe this image"
})
caption = caption_result[0]["generated_text"]

# Scene Understanding (BERT)
context = (
    f"The image shows {caption}. "
    f"It looks very [MASK]."
)

scene = text_generator(context)[0]["token_str"].strip()

# OCR Text Extraction
extracted_text = extract_text(image)

# Sentiment Analysis
if extracted_text:
    sentiment_result = sentiment_analyzer(extracted_text)
else:
    sentiment_result = sentiment_analyzer(caption)

sentiment = sentiment_result[0]["label"]


# OUTPUT

print("\n=========  AI ANALYSIS RESULT =========\n")

print(" Caption:")
print(caption)

print("\n Detected Objects:")
print(", ".join(set(objects)))

print("\n Scene Description:")
print(scene)

print("\n Extracted Text (OCR):")
print(extracted_text if extracted_text else "No text found")

print("\n  Sentiment:")
print(sentiment)


#  SPEAK OUTPUT

audio = speak(caption)
display(audio)

# Install pytesseract (Python library)
!pip install pytesseract

# Install Tesseract OCR engine (system package)
!apt-get install tesseract-ocr -y